// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv src/cloudflare-env.d.ts`

interface CloudflareEnv {
	STORYBLOK_CACHE: KVNamespace;
	TEST_VARIABLE: string;
	CLOUDFLARE_ZONE_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	ASSETS: Fetcher;
}
